export const GET_CAPSULES_DATA_REQUEST = "GET_CAPSULES_DATA_REQUEST";
export const GET_CAPSULES_DATA_SUCCESS = "GET_CAPSULES_DATA_SUCCESS";
export const GET_CAPSULES_DATA_FAILURE = "GET_CAPSULES_DATA_FAILURE";
